FROM node:23-alpine AS builder

ARG BUILD_DATE
ARG GIT_TAG
ARG GIT_BRANCH
ARG GIT_COMMIT_SHA
ARG GIT_LAST_COMMIT_DATE
ARG VITE_API_KEY_MAPBOX
ARG VITE_API_STYLE_MAPBOX_BLUEPRINT
ARG VITE_API_STYLE_MAPBOX_MSF
ARG VITE_API_STYLE_MAPBOX_GEO
ARG VITE_API_MAPTILER
ARG VITE_ROOT
ARG VITE_EMAIL
ARG VITE_VIDEO_TRAILER_HOME

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install

COPY public ./public
COPY src ./src
COPY i18n.js .
COPY index.html .
COPY postcss.config.js .
COPY site.config.js .
COPY tailwind.config.js .
COPY vite.config.js .


ENV NODE_ENV=production


ENV VITE_GIT_TAG=${GIT_TAG}
ENV VITE_GIT_BRANCH=${GIT_BRANCH}
ENV VITE_GIT_COMMIT_SHA=${GIT_COMMIT_SHA}
ENV VITE_GIT_LAST_COMMIT_DATE=${GIT_LAST_COMMIT_DATE}
ENV VITE_BUILD_DATE=${BUILD_DATE}
ENV VITE_API_KEY_MAPBOX=${VITE_API_KEY_MAPBOX}
ENV VITE_API_STYLE_MAPBOX_BLUEPRINT=${VITE_API_STYLE_MAPBOX_BLUEPRINT}
ENV VITE_API_STYLE_MAPBOX_MSF=${VITE_API_STYLE_MAPBOX_MSF}
ENV VITE_API_STYLE_MAPBOX_GEO=${VITE_API_STYLE_MAPBOX_GEO}
ENV VITE_API_MAPTILER=${VITE_API_MAPTILER}
ENV VITE_ROOT=${VITE_ROOT}
ENV VITE_EMAIL=${VITE_EMAIL}
ENV VITE_VIDEO_TRAILER_HOME=${VITE_VIDEO_TRAILER_HOME}
RUN npm run build

# print out these env values to a info.json file
RUN echo "{\"BUILD_DATE\": \"${BUILD_DATE}\", \"GIT_TAG\": \"${GIT_TAG}\", \"GIT_BRANCH\": \"${GIT_BRANCH}\", \"GIT_COMMIT_SHA\": \"${GIT_COMMIT_SHA}\", \"GIT_LAST_COMMIT_DATE\": \"${GIT_LAST_COMMIT_DATE}\", \"VITE_VIDEO_TRAILER_HOME\": \"${VITE_VIDEO_TRAILER_HOME}\"}" > dist/info.json

FROM busybox:stable
WORKDIR /app
COPY --from=builder /app/dist ./