name: Build and publish Docker image
on:
  # Trigger the workflow on push or pull request,
  # for the develop branch and all new tags
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get last commit date
        run: echo "GIT_LAST_COMMIT_DATE=$(git log -1 --format=%cd --date=format:%Y%m%d)" >> $GITHUB_ENV
      - name: Extract branch name
        run: echo "GIT_BRANCH=$(echo ${GITHUB_REF} | sed 's/refs\/heads\///')" >> $GITHUB_ENV
      - name: Extract commit hash
        shell: bash
        run: echo "GIT_COMMIT_SHA=$(git rev-parse --short ${GITHUB_SHA})" >> $GITHUB_ENV
        id: extract_hash
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          GIT_TAG: 'latest'
          GIT_BRANCH: ${{ env.GIT_BRANCH }}
          GIT_REVISION: ${{ steps.extract_hash.outputs.hash }}
        with:
          name: c2dhunilu/ww2
          token: ${{ secrets.DOCKERHUB_TOKEN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          buildargs: GIT_TAG,GIT_BRANCH,GIT_REVISION
          tags: 'latest'
